# Generated by Django 4.2 on 2023-06-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='num_of_activities',
            new_name='TotalActivities',
        ),
    ]
